In [55]:
# %pip install pandas openpyxl sklearn

In [56]:
import pandas as pd

In [57]:
data = pd.read_excel('C:\\Users\\Admin\\Desktop\\Automation\\TATA\\Task-1\\TATA_GENAI_DATA_ANALYSIS\\Task_1\\Delinquency_prediction_dataset.xlsx', engine='openpyxl')
data.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [58]:
data.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='str')

In [59]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    str
 1   Age                   500 non-null    int64
 2   Income                461 non-null    float64
 3   Credit_Score          498 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          471 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    str
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    str
 12  Location              500 non-null    str
 13  Month_1               500 non-null    str
 14  Month_2               500 non-null    str
 15  Month_3               500 non-null    str
 16  Month_4               500 non-null    str
 17  Month_5               500 non-null    str
 18  Month_6               500 non-null    str
dtypes: float64(5), int64(4), str(10)
memory usage: 74.3 KB

In [60]:
data.isnull().sum()

Customer_ID              0
Age                      0
Income                  39
Credit_Score             2
Credit_Utilization       0
Missed_Payments          0
Delinquent_Account       0
Loan_Balance            29
Debt_to_Income_Ratio     0
Employment_Status        0
Account_Tenure           0
Credit_Card_Type         0
Location                 0
Month_1                  0
Month_2                  0
Month_3                  0
Month_4                  0
Month_5                  0
Month_6                  0
dtype: int64

In [61]:
column_id = data['Customer_ID']

In [62]:
print(column_id)

0      CUST0001
1      CUST0002
2      CUST0003
3      CUST0004
4      CUST0005
         ...
495    CUST0496
496    CUST0497
497    CUST0498
498    CUST0499
499    CUST0500
Name: Customer_ID, Length: 500, dtype: str

In [63]:
data.drop(columns=['Customer_ID'], inplace=True)
data.head()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [64]:
data['Credit_Card_Type'].unique()

<StringArray>
['Student', 'Standard', 'Platinum', 'Gold', 'Business']
Length: 5, dtype: str

In [65]:
data['Credit_Card_Type'].isnull().sum()

np.int64(0)

In [66]:
credit_encoded_data = pd.get_dummies(data, columns=['Credit_Card_Type'], dtype = int)
credit_encoded_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        500 non-null    int64
 1   Income                     461 non-null    float64
 2   Credit_Score               498 non-null    float64
 3   Credit_Utilization         500 non-null    float64
 4   Missed_Payments            500 non-null    int64
 5   Delinquent_Account         500 non-null    int64
 6   Loan_Balance               471 non-null    float64
 7   Debt_to_Income_Ratio       500 non-null    float64
 8   Employment_Status          500 non-null    str
 9   Account_Tenure             500 non-null    int64
 10  Location                   500 non-null    str
 11  Month_1                    500 non-null    str
 12  Month_2                    500 non-null    str
 13  Month_3                    500 non-null    str
 14  Month_4                    500 non-null    str
 15  Month_5                    500 non-null    str
 16  Month_6                    500 non-null    str
 17  Credit_Card_Type_Business  500 non-null    int64
 18  Credit_Card_Type_Gold      500 non-null    int64
 19  Credit_Card_Type_Platinum  500 non-null    int64
 20  Credit_Card_Type_Standard  500 non-null    int64
 21  Credit_Card_Type_Student   500 non-null    int64
dtypes: float64(5), int64(9), str(8)
memory usage: 86.1 KB

In [67]:
credit_encoded_data.head()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,...,Month_2,Month_3,Month_4,Month_5,Month_6,Credit_Card_Type_Business,Credit_Card_Type_Gold,Credit_Card_Type_Platinum,Credit_Card_Type_Standard,Credit_Card_Type_Student
0,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,...,Late,Missed,Late,Missed,Late,0,0,0,0,1
1,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,...,Missed,Late,Missed,On-time,On-time,0,0,0,1,0
2,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,...,Late,Late,On-time,Missed,Late,0,0,1,0,0
3,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,...,Missed,Late,Missed,Late,Late,0,0,1,0,0
4,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,...,On-time,Missed,Late,Late,Late,0,0,0,1,0

In [68]:
credit_encoded_data['Employment_Status'].unique()

<StringArray>
['EMP', 'Self-employed', 'Unemployed', 'employed', 'Employed', 'retired']
Length: 6, dtype: str

In [69]:
credit_encoded_data['Location'].unique()

<StringArray>
['Los Angeles', 'Phoenix', 'Chicago', 'New York', 'Houston']
Length: 5, dtype: str

In [70]:
credit_encoded_data['Month_2'].unique()

<StringArray>
['Late', 'Missed', 'On-time']
Length: 3, dtype: str

In [71]:
month_map = {
    'Late' : 0,
    'Missed' : 1,
    'On-time' : 2
}
credit_encoded_data['Month_1'] = credit_encoded_data['Month_1'].map(month_map)
credit_encoded_data['Month_2'] = credit_encoded_data['Month_2'].map(month_map)
credit_encoded_data['Month_3'] = credit_encoded_data['Month_3'].map(month_map)
credit_encoded_data['Month_4'] = credit_encoded_data['Month_4'].map(month_map)
credit_encoded_data['Month_5'] = credit_encoded_data['Month_5'].map(month_map)
credit_encoded_data['Month_6'] = credit_encoded_data['Month_6'].map(month_map)

In [72]:
credit_encoded_data[['Month_1', 'Month_2', 'Month_3', 'Month_4', 'Month_5', 'Month_6']].head()

   Month_1  Month_2  Month_3  Month_4  Month_5  Month_6
0        0        0        1        0        1        0
1        1        1        0        1        2        2
2        1        0        0        2        1        0
3        0        1        0        1        0        0
4        1        2        1        0        0        0

In [73]:
encoded_data = pd.get_dummies(credit_encoded_data, columns=['Employment_Status', 'Location'], dtype = int)
encoded_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              500 non-null    int64
 1   Income                           461 non-null    float64
 2   Credit_Score                     498 non-null    float64
 3   Credit_Utilization               500 non-null    float64
 4   Missed_Payments                  500 non-null    int64
 5   Delinquent_Account               500 non-null    int64
 6   Loan_Balance                     471 non-null    float64
 7   Debt_to_Income_Ratio             500 non-null    float64
 8   Account_Tenure                   500 non-null    int64
 9   Month_1                          500 non-null    int64
 10  Month_2                          500 non-null    int64
 11  Month_3                          500 non-null    int64
 12  Month_4                          500 non-null    int64
 13  Month_5                          500 non-null    int64
 14  Month_6                          500 non-null    int64
 15  Credit_Card_Type_Business        500 non-null    int64
 16  Credit_Card_Type_Gold            500 non-null    int64
 17  Credit_Card_Type_Platinum        500 non-null    int64
 18  Credit_Card_Type_Standard        500 non-null    int64
 19  Credit_Card_Type_Student         500 non-null    int64
 20  Employment_Status_EMP            500 non-null    int64
 21  Employment_Status_Employed       500 non-null    int64
 22  Employment_Status_Self-employed  500 non-null    int64
 23  Employment_Status_Unemployed     500 non-null    int64
 24  Employment_Status_employed       500 non-null    int64
 25  Employment_Status_retired        500 non-null    int64
 26  Location_Chicago                 500 non-null    int64
 27  Location_Houston                 500 non-null    int64
 28  Location_Los Angeles             500 non-null    int64
 29  Location_New York                500 non-null    int64
 30  Location_Phoenix                 500 non-null    int64
dtypes: float64(5), int64(26)
memory usage: 121.2 KB

In [74]:
encoded_data.head()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure,Month_1,...,Employment_Status_Employed,Employment_Status_Self-employed,Employment_Status_Unemployed,Employment_Status_employed,Employment_Status_retired,Location_Chicago,Location_Houston,Location_Los Angeles,Location_New York,Location_Phoenix
0,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,18,0,...,0,0,0,0,0,0,0,1,0,0
1,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,0,1,...,0,1,0,0,0,0,0,0,0,1
2,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,1,1,...,0,1,0,0,0,1,0,0,0,0
3,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,15,0,...,0,0,1,0,0,0,0,0,0,1
4,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,11,1,...,0,1,0,0,0,0,0,0,0,1

In [75]:
encoded_data.columns

Index(['Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Account_Tenure', 'Month_1', 'Month_2',
       'Month_3', 'Month_4', 'Month_5', 'Month_6', 'Credit_Card_Type_Business',
       'Credit_Card_Type_Gold', 'Credit_Card_Type_Platinum',
       'Credit_Card_Type_Standard', 'Credit_Card_Type_Student',
       'Employment_Status_EMP', 'Employment_Status_Employed',
       'Employment_Status_Self-employed', 'Employment_Status_Unemployed',
       'Employment_Status_employed', 'Employment_Status_retired',
       'Location_Chicago', 'Location_Houston', 'Location_Los Angeles',
       'Location_New York', 'Location_Phoenix'],
      dtype='str')